function raiz = cmc_prepara_entorno_r2011a
%CMC_PREPARA_ENTORNO_R2011A Usa solo la copia portable antes de una prueba.

raiz = fileparts(mfilename('fullpath'));
restoredefaultpath;
addpath(raiz);
addpath(fullfile(raiz, 'Valentia'));
addpath(fullfile(raiz, 'Valentia', 'valentia'));
cd(raiz);

funciones = { ...
    'abrir1', ...
    'OA_ValentiaCuatroE', ...
    'OA_ValentiaCuatroE2', ...
    'OA_Condiciona_Aleatorio', ...
    'OA_ValentiaInicio', ...
    'OA_Sonidos', ...
    'OA_ValentiaEstimuloI', ...
    'OA_ValentiaEstimuloD', ...
    'OA_ValentiaElectrico'};

for k = 1:length(funciones)
    ruta = which(funciones{k});
    if isempty(ruta) || ~strncmpi(ruta, raiz, length(raiz))
        error('CajaValentia:Rutas', ...
            'La funcion %s no proviene de la copia del Escritorio: %s', ...
            funciones{k}, ruta);
    end
end

fprintf('CajaValentia: usando solo la copia del Escritorio:\n%s\n', raiz);

