function cmc_prueba_conteo_cruces_validos
%CMC_PRUEBA_CONTEO_CRUCES_VALIDOS Verifica que solo los cruces validos sumen.

assert(cmc_es_cruce_valido(0,'I','I',1.0), ...
    'Un cambio de lado lateral de al menos un segundo debe contar.');
assert(cmc_es_cruce_valido(0,'D','D',1.2), ...
    'El criterio debe funcionar para ambos lados.');
assert(~cmc_es_cruce_valido(0,'I','I',[]), ...
    'Un no-cruce no debe contar.');
assert(~cmc_es_cruce_valido(1,'I','I',1.2), ...
    'Una repeticion del mismo lado no debe contar.');
assert(~cmc_es_cruce_valido(0,'C','I',1.2), ...
    'Un inicio desde la zona central no debe contar.');
assert(~cmc_es_cruce_valido(0,'I','I',0.99), ...
    'Un desplazamiento menor a un segundo no debe contar.');

assert(~cmc_objetivo_cruces_alcanzado(29,30), ...
    'Veintinueve cruces no deben finalizar un objetivo de treinta.');
assert(cmc_objetivo_cruces_alcanzado(30,30), ...
    'Treinta cruces deben finalizar un objetivo de treinta.');
assert(cmc_objetivo_cruces_alcanzado(31,30), ...
    'El objetivo debe mantenerse alcanzado despues del cruce treinta.');
