function evento = cmc_evento_palanqueo(eventoSesion, tiempo_s, fase, ensayo, tipoEvento, lado, contadorLadoSesion, contadorHardware)
%CMC_EVENTO_PALANQUEO Crea una fila autocontenida para el registro de conducta.

evento = struct('evento_sesion', eventoSesion, 'tiempo_s', tiempo_s, ...
    'fase', fase, 'ensayo', ensayo, 'tipo_evento', tipoEvento, ...
    'lado', lado, 'contador_lado_sesion', contadorLadoSesion, ...
    'contador_hardware', contadorHardware);
